# Generated by Django 2.2.13 on 2020-06-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='sdfwafe',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='sfdwaf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
