# Generated by Django 2.2.13 on 2020-06-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200619_0514"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="sfdwaf",),
    ]
