# Generated by Django 2.2.13 on 2020-06-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200619_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='sfdwaf',
        ),
    ]
