# Generated by Django 2.2.13 on 2020-06-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_customtext_sfdwaf"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="fgwsrg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="jhglkhgljg",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
