# Generated by Django 2.2.13 on 2020-06-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_auto_20200619_0520"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="nbvhbv",),
        migrations.RemoveField(model_name="homepage", name="sdcasc",),
    ]
